#
# $Id$
#
#
OBJ=sp_io_vars.o sp_io.o sp_init.o sp_main.o

LIBRARY=libspace.a

HEADERS=sp_adios_common.fh

LIB_INCLUDES=`adios2-config -f`

USES_BLAS=

include ../config/makefile.h

include ../config/makelib.h
