#!/bin/bash
#set -x
########################################################################
#   Batch Job Parameters
########################################################################
#
#### Grid Engine Job Wrapper ####
#
#$ -N 7cz4_eq
#$ -pe mpi2 1
#$ -q wp08
#$ -j y
#$ -m e
#$ -v LD_LIBRARY_PATH,OMP_NUM_THREADS
#
#### Torque/PBS Job Parameters ####
#
#PBS -N 7cz4_eq
#PBS -l nodes=n023:ppn=16
#
########################################################################
#   Batch Environment Initialization Commands
########################################################################
#
#### Grid Engine Initialization Commands ####
#
if [ -f $TMPDIR/sge_init.sh ]; then
    source $TMPDIR/sge_init.sh
fi
#
#### Torque/PBS Initialization Commands ####
#
if [ ! -z $PBS_JOBID ]; then
    cd $PBS_O_WORKDIR
fi
#
########################################################################
#   Job Execution Commands
########################################################################
#
export OMP_NUM_THREADS=1
export GMON_OUT_PREFIX="gmon_md"
#echo "LD_LIBRARY_PATH="$LD_LIBRARY_PATH
echo "PWD"
pwd
echo "LS"
ls -l /home/hvandam/nwchem-1-pretauadio2/QA/tests/7cz4/7cz4_eq.nw
echo "NWCHEM"
mpiexec -n 16 -x LD_LIBRARY_PATH /home/hvandam/nwchem-1-pretauadio2/bin/LINUX64/nwchem /home/hvandam/nwchem-1-pretauadio2/QA/tests/7cz4/7cz4_eq.nw 2>&1 > 7cz4_eq.out
